### ISSUE TITLE
!cmd() Not Working on v1.2

### ISSUE THREAD

**Issue by tajmone** [CDSoft/pp#10]
The documentation says that `!bat()` is deprecated in favour of `!cmd()` but with latest build (PP v1.2) the former works and the latter fails.

Is it due to the fact that the latest build doesn't implement it?

Could you release binaries for the updated version?

Thanks

**Comment by tajmone** [comment]
I've downloaded the binary from http://cdsoft.fr/pp/ and `!cmd()` works.

Are the binaries available on cdsoft.fr always updated to the actual source?

**Comment by CDSoft** [comment]
The binary on cdsoft.fr is built from my local repository. Unless the latest version is not pushed to github, sources and binaries should be the same. The binary on cdsoft.fr can be outdated if I forget to upload it.
I have just cloned my github repository and it seems to be uptodate (both cmd and bat work).
Can you please try to make a fresh clone to see if this fixes your problem?
The tag 1.2 is not necessarily the latest version. I increment the version number only for new features (I didn't consider that !cmd is a new feature, maybe I should).
The latest version is 1.2-**10**-gde27725. Which mean that there are 10 commits after v1.2.

**Comment by tajmone** [comment]
Yes, it works fine.

Thanks. I just needed to know where to link to because I'm working on some PP macros I want to publish, and since they use new `!cmd()` built-in macro I must provide a link to the newer pre-release (instead of still using `!bat()`, so I don't have to update the macros when it becomes deprecated).

**Comment by CDSoft** [comment]
I have released the version 1.3 that also support reStructuredText. Now the binary is the one of the latest release... until the next one ;-)
