### ISSUE TITLE
PP-Macros Library

### ISSUE THREAD

**Issue by tajmone** [CDSoft/pp#13]
I finally managed to publish my first collection of pp-macros:

- https://github.com/tajmone/pandoc-goodies/tree/master/pp

The pandoc template preview is built using the pp macros, so it also offers a good example.

There are other macros almost ready, just need some time to polish them before pushing.

Hopefully, this could be the beginning of a collaborative effort to create a library of cross-platform, cross-format pp macros. At the moment, the macros are for HTML output only, and a couple of them work for Windows only (beacuse of the `!cmd` macro), but I'll soon try to fix them so they can be OS aware and use the right script macro.

As with all project ... creating and polishing the minimum README files, draft some documentation, and check that all third party licenses were honored, took up more time than actually writing the macros or the template. But now that this is out of the way, progresses should be faster.

**Comment by tajmone** [comment]
Here is the link to an HTML Preview (via htmlpreview.github.io) of how the pandoc template can use pp-macros to emulate GFM Task Lists with pandoc, and GitHub's alerts:

https://htmlpreview.github.io/?https://github.com/tajmone/pandoc-goodies/blob/master/templates/html5/github/GitHub-Template-Preview.html#task-lists

**Comment by CDSoft** [comment]
I like the task list!
I have added a link in the documentation.
