### ISSUE TITLE
Download from Homepage is missing tag.sh

### ISSUE THREAD

**Issue by suhlig** [CDSoft/pp#36]
As advised by [the docs](http://cdsoft.fr/pp/) I downloaded pp from http://cdsoft.fr/pp/pp.tgz and extracted it; yet `make` failed with

```bash
/bin/bash: ./tag.sh: No such file or directory
make: *** No rule to make target `.stack-work/PlantumlJar_c.c', needed by `/Users/suhlig/Downloads/pp/.stack-work/install/x86_64-osx/lts-9.1/8.0.2/bin/pp'.  S
top.
```

Looks like the tarball does not include `tag.sh`. Cloning the git repo worked fine, so I guess the tarball is incomplete?

**Comment by CDSoft** [comment]
tag.sh should not be executed outside of a git repository. I will fix Makefile.

I don't understand the second error. I can reproduce it but I don't see any difference between the tarball and the git repository... Need more time to understand.

**Comment by CDSoft** [comment]
Oops I just have seen that tools/blob.hs is missing too. That fixes the second error.
