### ISSUE TITLE
Installation in Ubuntu complains about stack

### ISSUE THREAD

**Issue by lf-araujo** [CDSoft/pp#46]
Ho to circumvent the compile error:

```
#### converting .stack-work/Plantuml.jar to C
stack tools/blob.hs .stack-work/Plantuml.jar
/bin/bash: stack: comando não encontrado
Makefile:127: recipe for target '.stack-work/PlantumlJar_c.c' failed
make: *** [.stack-work/PlantumlJar_c.c] Error 127

```

I can't find stack with apt, is there a place where I can obtain it?

**Comment by CDSoft** [comment]
The link to the stack home page is here: https://github.com/CDSoft/pp/blob/master/README.md#installation

It describes the installation procedure.

Le 8 novembre 2017 08:23:23 GMT+01:00, lf_araujo <notifications@github.com> a écrit :
>Ho to circumvent the compile error:
>
>```
>#### converting .stack-work/Plantuml.jar to C
>stack tools/blob.hs .stack-work/Plantuml.jar
>/bin/bash: stack: comando não encontrado
>Makefile:127: recipe for target '.stack-work/PlantumlJar_c.c' failed
>make: *** [.stack-work/PlantumlJar_c.c] Error 127
>
>```
>
>I can't find stack with apt, is there a place where I can obtain it?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CDSoft/pp/issues/46

-- 
Christophe Delord

**Comment by lf-araujo** [comment]
Thank you
