### ISSUE TITLE
How to define a macro that accepts link_attributes?

### ISSUE THREAD

**Issue by lf-araujo** [CDSoft/pp#47]
Thank you for the help and for the tool.

I am trying to define a macro that accepts link_attributes (thinking of width=30%), but how do I do that?

The following macro:

```
!define(figure)
(
\begin{figure}
\includegraphics{!2}
\caption{!1}
\end{figure}
)
```

Naturally breakes the preprocessing if it is called with:
`
!img(Exports and Imports to and from Denmark & Norway from 1700 to 1780)(source/figures/exports-imports.png { width = 20% } )`

- How do you suggest I should go about adding this functionality to the above macro?

**Comment by CDSoft** [comment]
What about using a third optional parameter for the link attributes?

In the macro:

    !ifdef(3)(do something with !3)

The macro could be called as:

     !img(Exports and Imports to and from Denmark & Norway from 1700 to 1780)(source/figures/exports-imports.png)( width = 20% )
