### ISSUE TITLE
Question: Passing options to diagram renderers

### ISSUE THREAD

**Issue by bpj** [CDSoft/pp#49]
Is it possible to pass options to diagram renderers (e.g. `--no-shadows` to ditaa)? If not is it something you might consider adding?

**Comment by CDSoft** [comment]
It's currently not possible. But most of the diagram languages can have the same effect by using commands in the script itself.
ditaa is not directly embedded in pp, I now use the ditaa version that comes with plantuml (see http://plantuml.com/ditaa). You can pass options to ditaa like this:

    !uml(image)
    ~~~~~
    ditaa(--no-shadows, scale=0.8)
    /--------\   +-------+
    |cAAA    +---+Version|
    |  Data  |   |   V3  |
    |  Base  |   |cRED{d}|
    |     {s}|   +-------+
    \---+----/
    ~~~~~

In this example, options are handled by plantuml (hence `!uml`), not by pp.
