### ISSUE TITLE
!usermacros: Omit Macros Whose Name Starts with Underscore

### ISSUE THREAD

**Issue by tajmone** [CDSoft/pp#51]
When building a set of macros, sometimes I also add some "internal" macros — ie: macros not intended to be used by endusers, but just by the macros, for secondary tasks. Usually I give these internal macros names starting with an underscore, to distinguish them from the actual enduser macros.

I was thinking that it would be nice if `!usermacros` and `!userhelp` would ignore macros starting with an "`_`". This would help keeping a clean auto-generated documentation, without showing certain macros. My guess is that usually no one would use such a naming convention unless it was some sort of internal-usage stuff, therefore it shouldn't interfere with most existing macros collections.

**Comment by CDSoft** [comment]
`!userhelp` lists only macros that have been documented. Should `!usermacros` also list only documented macros?
Unexported macros could then be commented but not documented.

**Comment by tajmone** [comment]
>  Should `!usermacros` also list only documented macros?

No, I think that most users would expect `!usermacros` to list all user defined macros. Some macros might have a self-explaining name and need not be documented. But the idea is interesting, and maybe having also a `!documentedusermacros` could be useful in the context of auto-generated documentation.

The idea of underscored macros being unlisted by any of the above built-in macros is strictly related to their being internal use only macros.

But I'm suggesting this based on my way of doing things, and assuming that having an underscore as first name character would seem a special use-case to most people, and that some internal macros need not be exposed to user documentation.

**Comment by CDSoft** [comment]
pp 2.2.1 does not list user macros starting with `_`.
