### ISSUE TITLE
How to use asymptote with other formats than png

### ISSUE THREAD

**Issue by geniusupgrader** [CDSoft/pp#55]
I want to use svg generated from pp and asymptote.
But pp always append png to the filename.
How to use asymptote with other formats than png?

**Comment by CDSoft** [comment]
Currently pp generates only PNG images. There were two options for Asymptote: PDF or other formats. The advantage of PDF is that it accepts transparency. So internally pp makes asymptote generate PDF files converted to PNG to be accepted by pandoc.
I can try to change the output format. e.g. if the format is given in the image name it will be used to generate the image (when possible).

**Comment by geniusupgrader** [comment]
> I can try to change the output format. e.g. if the format is given in the image name it will be used to generate the image (when possible).

yeah specify format in the image name, I think also this would be best way.

**Comment by CDSoft** [comment]
I have a patch to use PNG and SVG formats. I'm wondering if SVG shouldn't become the default format for diagrams when available (files are smaller). Asymptote diagrams with transparency should be given the PNG extension explicitly.

**Comment by geniusupgrader** [comment]
> I'm wondering if SVG shouldn't become the default format for diagrams when available (files are smaller)

I have no problem with that...

**Comment by CDSoft** [comment]
done in v. 2.3

**Comment by geniusupgrader** [comment]
Thanks

**Comment by bpj** [comment]
Note that most (all?) LaTeX engines barf at SVG. They want PDF.

**Comment by geniusupgrader** [comment]
@bpj you are correct, but when using pandoc, it automatically converts svg files to pdf, I think it is doing it with [librsvg](https://en.wikipedia.org/wiki/Librsvg), see [here](https://github.com/jgm/pandoc/issues/1793).

There are not so many open vector formats and svg is propably the way to go in the web. So the svg format is the lowest common denominator for output formats I use most often: html and pdf.

**Comment by CDSoft** [comment]
I have added PDF in diagram formats (pp 2.3.1). But it may not work with PlantUML. If you want PDF, you have to explicitly add the `.pdf` extension to image names.

**Comment by geniusupgrader** [comment]
> I have added PDF in diagram formats

Can you elaborate? Do you mean its the standard now?

**Comment by CDSoft** [comment]
No, PDF is just one possible output format. The default format is still SVG.

**Comment by CDSoft** [comment]
Well I think that the default format should take the output format into account. To make a PDF document, pandoc uses LaTeX. In this case the default image format should be PDF or PNG.
