### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by holmboe** [CDSoft/pp#57]
There are pre-built binaries provided for Windows and Linux at the CDSoft website, which is nice, but there are two problems I would like to raise:

1. The downloads are provided on a unencrypted, and therefore [MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack):able, connection. Please use HTTPS.
2. The downloads are not versioned, e.g. downloading http://cdsoft.fr/pp/pp-linux-x86_64.txz does not reveal which version I am downloading. Please use `pp_latest_linux-amd64.txz`, but also provide `pp_2.3.4_linux-amd64.txz` (note that I adapted the filename similar to the Debian naming convention to separate the name, version and architecture). This way I am able to download previously released binaries.

I would also recommend using the [releases-page on your GitHub project](https://github.com/CDSoft/pp/releases) to host those pre-built binaries.

My use-case for the above request is that I want to include your preprocessor in an automated build system and want to make sure that I get the same `pp` each time I refresh my build environment.

**Comment by tajmone** [comment]
As for point 2, the download page offers binaries downloads with files named with version:

http://cdsoft.fr/pp/download.html

The link you mentioned is to get the latest release, but previous releases are always available. I too have created a project that relies on specific versions of PP, and therefore use the links found at the download page (older versions are kept for download).

**Comment by holmboe** [comment]
Summary: it seems that 2 was already solved and 1 was solved by adding HTTPS to the instructions at http://cdsoft.fr/pp/index.html#installation

Thanks @CDSoft and @tajmone
