### ISSUE TITLE
PP Tutorial

### ISSUE THREAD

**Issue by tajmone** [CDSoft/pp#6]
Hi Christophe,

just wanted to let you know that I've published a first draft of my PP tutorial:

https://github.com/tajmone/markdown-guide/tree/master/pp

It could still be continued, but it's a good starting point for absolute novices. (It might not be over-polished right now, I didn't have time to fully revise it, but I though it was best to just publish it).

In the future (time permitting) I'm planning to add more examples and also some custom scripts (eg: for redirecting source code to external syntax highlighters, ecc.).

The tutorial is public domain, so feel free to plunge from it at will — I've decided to make the project public domain because I don't want people to strugle with quotations, or to constantly feeling obliged to quote the source. Just take and use what you like.

B.R.

**Comment by CDSoft** [comment]
Thanks,
I've added a link to the tutorial in the documentation.

**Comment by CDSoft** [comment]
Not really an issue ;-)
I close it.
