### ISSUE TITLE
Strange codes in README.md

### ISSUE THREAD

**Issue by albert-github** [CDSoft/pp#75]
In the README.md there are a few strange codes.
On the lines 283, 342, 345, 46, 460, 466 and 601 we see `e.g.` and `i.e.` followed by a <space> but when examining the code we see on the place of the space the code 302 240
- does this code have a special meaning in markdow / pp ?

**Comment by CDSoft** [comment]
This is the [UTF-8 no-break space character](http://www.fileformat.info/info/unicode/char/00a0/index.htm). It must have been generated by pandoc.

**Comment by albert-github** [comment]
Thank you for the answer, I overlooked apparently this sequence when I searched for it.
