### ISSUE TITLE
PP v2.8 Binary Release Doesn't Contain EXE file

### ISSUE THREAD

**Issue by tajmone** [CDSoft/pp#77]
Latest PP (2.8) for Windws downloadable from the PP binaries download page contains only html documentation, no binary file:

http://cdsoft.fr/pp/download.html

Tried both the latest version link as well as v2.8.

**Comment by tajmone** [comment]
Same problem with version 7.4 — from v7.3 downward all archives contain the binary executable.

**Comment by CDSoft** [comment]
Fixed.

**Comment by tajmone** [comment]
Thanks! I confirm, PP 2.8 working on Win 10 x64.
