### ISSUE TITLE
Fails to build on Debian testing

### ISSUE THREAD

**Issue by hoijui** [CDSoft/pp#81]
latest master as of 5. July 2019: 73a5e42d66bf99c7dbd1aec26ff80dd3566a91c8

```
[OK] /home/user/src/pp/.stack-work/install/x86_64-linux-tinfo6/lts-13.20/8.6.5/bin/pp
#### preprocessing doc/pp.md
stack exec -- pp -en -img=doc/img -DRESOLVER=lts-13.20 -DREADME doc/pp.md | pandoc -f markdown -t gfm > README.md
cat: /etc/redhat-release: No such file or directory
pp: Error while executing `lua /tmp/pp11710-7.lua`: lua: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
make: *** [Makefile:96: README.md] Error 1
make: *** Deleting file 'README.md'
```
`uname -a`
> Linux hostname 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Comment by hoijui** [comment]
strangely, some part of the build process deleted `README.md`, adn on a later run, `doc/pp.html` was deleted.

**Comment by CDSoft** [comment]
README.md and pp.html are generated from pp.md. In case of failure, make deletes any partially generated file.
If you build the documentation you need some dependencies (lua, python, bash, wine, ...) to build the example of the documentation.
If you just need to install the binary, just run `make install`.

Note: the build system has been made to run on my machine (Fedora). On other platforms, the documentation may not be correctly generated. This should have no impact on the binary.

**Comment by hoijui** [comment]
thank you! :-)
that worked indeed!

I made a pull request to have `make` (without arguments) do the commonly assumed default of just building (what gets installed with `make install`).

thank you for `pp`! :-)
we are most likely going ot use it for the documentation generation workflow of many porjects.

**Comment by CDSoft** [comment]
Thanks for the pull request.
I think I'll go a little bit further and add explicit targets to compile, test, document and distribute pp. The default target being the compile target.

**Comment by hoijui** [comment]
nice! :-)

**Comment by CDSoft** [comment]
done in pp 2.10

**Comment by hoijui** [comment]
tested, works.. thank you! :-)
