### ISSUE TITLE
Temporarily suspend printing text via storage/recall macros?

### ISSUE THREAD

**Issue by RHagenson** [CDSoft/pp#87]
Is there a way to temporarily store the processed text of a macro rather than print it immediately then later recall all the stored text?

Contrived (but simplified example):

```
!define(firstname)(!store(stored-firstname)(_!1_))
!define(middlename)(!store(stored-middlename)(~!1~))
!define(lastname)(!store(stored-lastname)(**!1**))
!define(printname)(!recall(stored-firstname) !recall(stored-middlename) !recall(stored-lastname))
```

The `!printname` would appear as: _First_ ~Middle~ **Last**

One increment better would be a way to define the new storage macros based on the name of the macros used to store them then recall based on pattern match. E.g. `!define(firstname)(!store(names-)(!1))` (creates a macros called `names-firstname`) then later `!recall(names-)(firstname)` to recall a single entry under "names "or `!recall(names-)` to recall all entries (in order they were entered).

**Comment by bpj** [comment]
I believe you are looking for !append.

Use it like so:

!undef(_temp)
!append(_temp)(!capture_my_output)

and then later just use !_temp (which of course can be called anything!) to
insert the stored value.

Den tors 3 okt. 2019 22:46Ryan A. Hagenson <notifications@github.com> skrev:

**Comment by RHagenson** [comment]
I kind of figured there was a way to do this already, just not the worded the same way I had in my head. I will look into the !append macro. Thank you.
