### ISSUE TITLE
FYI: working on a Homebrew formula

### ISSUE THREAD

**Issue by albins** [CDSoft/pp#93]
Thanks for your work!

I have started working on a Homebrew formula for pp, and have something working (but probably not conforming to all the requirements of the homebrew team), and wanted to let you know about it.

Currently I bypass the Makefile to avoid external downloads, which Homebrew does not allow. Instead, I use plantuml and ditaa from their Homebrew packages (declared as build-dependencies), and their packaged GHC.

I also rename the binary to cdsoft-pp to avoid naming collissions with the system package pp that apparently comes with macOS. Do you have any preferences here?

**Comment by CDSoft** [comment]
Thanks.
Do not hesitate to make a pull request if you wish your homebrew formula to be included. It may be a separate script or makefile.

**Comment by albins** [comment]
I think it will reside in the homebrew repository, but I would appreciate your input on my PR there once it's done. For now, I am a bit stalled though and might not be able to do much until August due to vacations and other things.

**Comment by CDSoft** [comment]
Ok. I'll close the issue. You can make a new one when the Homebrew formula is ready.

**Comment by lclem** [comment]
hello @albins, any developments on this one? :)

**Comment by albins** [comment]
@lclem I kind of gave up; I have a working formula that builds and installs on my machine (tm), and that I think patches some of the remote fetching, but I realised that getting rid of all the things that are automatically fetched on build would take more time and energy than I had. You are very welcome to keep working on my formula if you want to!
