### ISSUE TITLE
Markdown header shifting on file inclusion

### ISSUE THREAD

**Issue by lmunch** [CDSoft/pp#97]
A header shifting feature like MarkdownPP has could be really useful. See https://github.com/jreese/markdown-pp#includes for an example

**Comment by CDSoft** [comment]
There is no plan to add a markdown parser to pp. May I suggest to have a look at https://github.com/CDSoft/abp ?
With abp, you can write things like:

    :::{include="file.md" shift=2}
    :::

**Comment by lmunch** [comment]
That is perfect. Do not know how I missed abp. Thanks
